# Generated by Django 4.1.1 on 2023-03-06 19:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openphrase',
            name='id',
            field=models.UUIDField(default=uuid.UUID('00a0e978-30fa-45ef-b44a-395f3348ba14'), primary_key=True, serialize=False),
        ),
    ]
